services:
  - type: web
    name: careflow-backend
    env: node
    buildCommand: npm ci && npx prisma generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false # Render will prompt for this value
      - key: REDIS_URL
        fromService:
          type: redis
          name: careflow-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: WORKER_API_KEY
        generateValue: true
      - key: CSRF_SECRET
        generateValue: true
      - key: SENTRY_DSN
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        sync: false
      - key: AWS_S3_BUCKET
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: https://careflow-frontend.vercel.app,http://localhost:3000
      - key: MAX_FILE_SIZE
        value: 10mb
      - key: API_VERSION
        value: 1.0.0
      - key: LOG_LEVEL
        value: info
      - key: RATE_LIMIT_WINDOW
        value: 15
      - key: RATE_LIMIT_MAX
        value: 100
      - key: AUTO_MIGRATE
        value: true
      - key: SEED_DATABASE
        value: false
      - key: DB_DIALECT
        value: postgres
      - key: DB_PROTOCOL
        value: postgres
      - key: DB_SSL
        value: true
    healthCheckPath: /api/health
    autoDeploy: true
    disk:
      name: uploads
      mountPath: /app/uploads
      sizeGB: 10
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 80
      targetCPUPercent: 80
    buildFilter:
      paths:
        - src/**
        - config/**
        - models/**
        - routes/**
        - middleware/**
        - utils/**
        - package.json
        - package-lock.json
        - .env.example
        - README.md
        - render.yaml
    headers:
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
      - path: /*
        name: Strict-Transport-Security
        value: max-age=31536000; includeSubDomains
      - path: /*
        name: Content-Security-Policy
        value: default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' https: data:; connect-src 'self' https://*.onrender.com; frame-src 'none'; object-src 'none'; media-src 'self'; sandbox allow-forms allow-scripts allow-same-origin
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /*
        name: Permissions-Policy
        value: geolocation=(), microphone=(), camera=()
    healthCheck:
      path: /health
      intervalSeconds: 30
      timeoutSeconds: 10
      gracePeriodSeconds: 60
      maxConsecutiveFailures: 3

  - type: redis
    name: careflow-redis
    ipAllowList: []
    plan: free
    region: oregon

databases:
  - name: careflow-db
    databaseName: careflow
    user: careflow
    plan: free
    region: oregon
    ipAllowList: [] 